import Head from 'next/head'
import Nav from './components/nav'
import Content from './components/content'
import styles from '../styles/dev.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <Nav/>
      <Content/>

    </div>
  )
}